### ISSUE TITLE
error of  run generate_ Outputs_ Gpt2. py 

### ISSUE THREAD

**Issue by Double-Sail** [kobzaond/e2e_transformer_nlg#2]
Run generate_ Outputs_ Gpt2. py, the following error will occur:
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [624,0,0], thread: [32,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

Then trigger the assertion error:
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

I hope you can provide assistance, thank you very much!

**Comment by Double-Sail** [comment]
The problem has been resolved, and the tokenizer needs to be replaced with the original model's tokenier instead of the generated one
